CREATE TABLE [dbo].[Crop] (
    [Id]   INT           NOT NULL,
    [Name] VARCHAR (255) NOT NULL,
    [Created_At] DATETIME2 NULL DEFAULT CURRENT_TIMESTAMP, 
    [Updated_At] DATETIME2 NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

